server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:prolog-idp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comment: false
  h2:
    console:
      path: /h2
      enabled: true

github:
  url:
    access-token: http://localhost:8081/github/login/oauth/access_token
    profile: http://localhost:8081/github/user
  client:
    id: github-client-id
    secret: github-client-secret
